import type {
  SimpleEmployee,
  RetrieveInfoVO,
  TerminationVO,
  StateLaw,
  PendingTermination,
  LeavePlan,
  EarningsEntry,
  WizardFormData,
} from "./types";

export const mockEmployee: SimpleEmployee = {
  empId: "00010054747",
  lastName: "Alonso-Garcet",
  firstName: "Melamie",
  phoneNumber: "11111111111 (H)",
  emailAddr: "DevEmailTesting@trinet.com",
  emplStatus: "A",
  locationId: "W000002DNR",
  primaryFirstName: null,
  primaryLastName: null,
  hccLastName: null,
  hccFirstName: null,
  hccPhoneNumber: null,
  hccEmailAddr: null,
  termStatus: "new",
  serviceDt: "2020-10-20",
  lastHireDate: "2020-10-20",
};

export const mockRetrieveInfo: RetrieveInfoVO = {
  address1: "8867 E Briarwood Ct",
  address2: " ",
  city: "Vista",
  homeState: "CA",
  postalCd: "92083",
  dollarEarningCodes: [
    { erncd: "AB", desc: "Discretionary Annual Bonus", paymentType: "A", prcCategory: "", hrsOnly: "N", multiFactor: 0, addToGross: "Y", perUnitRate: "0" },
    { erncd: "ADM", desc: "Admin Pay", paymentType: "A", prcCategory: "", hrsOnly: "N", multiFactor: 0, addToGross: "Y", perUnitRate: "0" },
    { erncd: "BNH", desc: "Nondiscretionary Hiring Bonus", paymentType: "A", prcCategory: "", hrsOnly: "N", multiFactor: 0, addToGross: "Y", perUnitRate: "0" },
    { erncd: "BNR", desc: "Nondiscretionary Retention BNS", paymentType: "A", prcCategory: "", hrsOnly: "N", multiFactor: 0, addToGross: "Y", perUnitRate: "0" },
    { erncd: "MVT", desc: "Relocation-Taxable", paymentType: "A", prcCategory: "", hrsOnly: "N", multiFactor: 0, addToGross: "Y", perUnitRate: "0" },
    { erncd: "RFB", desc: "Discretionary Referral Bonus", paymentType: "A", prcCategory: "", hrsOnly: "N", multiFactor: 0, addToGross: "Y", perUnitRate: "0" },
    { erncd: "RLN", desc: "Relocation EXPN Taxable", paymentType: "A", prcCategory: "", hrsOnly: "N", multiFactor: 0, addToGross: "Y", perUnitRate: "0" },
  ],
  hourEarningCodes: [
    { erncd: "ADH", desc: "Admin Pay Hours", paymentType: "H", prcCategory: "", hrsOnly: "Y", multiFactor: 1, addToGross: "Y", perUnitRate: "0" },
    { erncd: "BRV", desc: "Bereavement", paymentType: "H", prcCategory: "", hrsOnly: "Y", multiFactor: 1, addToGross: "Y", perUnitRate: "0" },
    { erncd: "HOL", desc: "Holiday", paymentType: "H", prcCategory: "", hrsOnly: "Y", multiFactor: 1, addToGross: "Y", perUnitRate: "0" },
    { erncd: "OVT", desc: "Overtime", paymentType: "H", prcCategory: "", hrsOnly: "N", multiFactor: 1.5, addToGross: "Y", perUnitRate: "0" },
    { erncd: "PTO", desc: "PTO", paymentType: "H", prcCategory: "", hrsOnly: "Y", multiFactor: 1, addToGross: "Y", perUnitRate: "0" },
    { erncd: "REG", desc: "Regular", paymentType: "H", prcCategory: "", hrsOnly: "N", multiFactor: 1, addToGross: "Y", perUnitRate: "0" },
  ],
  unitEarningCodes: [],
};

export const mockTerminationVO: TerminationVO = {
  personId: "00010054747",
  positionId: "00010054747",
  hrAuthId: null,
  companyId: null,
  uniqueId: 0,
  termVoSubEmpInfo: {
    endDt: "2099-12-31",
    effDt: null,
    mgdEvent: "TER",
    mgdReason: null,
    emplymntStatus: "A",
    dateContacted: null,
    death: null,
    dateGaveNotice: null,
    lastWorkDate: null,
    emailAddr: null,
    othAddr1: null, othAddr2: null, othCity: null,
    othStateProvinceCd: null, othCountryCd: null, othPostalCd: null,
    rehireEligibility: null,
    referrerCode: " ",
    workPeriod: "W",
  },
  termVoSubBenefits: { estBenefName: null, estBenefTaxId: null },
  termVoSubPayBal: {
    ptoHrsTaken: null, vacHrsTaken: null, sickHrsTaken: null,
    finalHoursWorked: null, totalFinalHrs: null, finalOtHoursWorked: null,
    curPtoAdjust: null, curPtoAdjust2: null, ptoBalance: null,
    curPtoBalance: null, curPtoBalance2: null, negPtoBalance: null,
    payPtoBalance: null, sickBalance: null, paySickBalance: null,
    negSickBalance: null,
  },
  termVoSubPay: {
    payThroughDate: null, othPay: null, additionalPay: null,
    additionalDescr: null, finalCheckDist: null, othChkDistAddr: null,
    finalReimburse: null, othChkDistName: null, payAccruedLvHrs: null,
    hoursEarning: null, dollarsEarning: null, totalFinalDollars: null,
    equalPayment: null, checkDate: null, sameCheckDate: null,
    addlSeparateCk: null, commissionSeparateCk: null, bonusSeparateCk: null,
    payUfhAccruedHrs: null, paymentMethod: null, deliveryMethod: null,
    deliveryIstr: null, additionalPayCode: null, directDepositEndDate: null,
    offCycle: null, paymentCycleCheckDate: null, inHouseCkType: null,
    inHouseCkAmount: null, inHouseCkContact: null, inHouseCkAttachment: null,
    finalPayPeriodEarnings: null, previousPayPeriodEarnings: null,
    finalPayDueDate: null, firstPaymentDate: null, lastPaymentDate: null,
  },
  termVoSubMgr: { hrmContacted: null, hrmName: null, mgrName: null },
  termVoSubProcess: {
    confirmSendEmail: null, emailAddress: null, emailSent: null,
    notes: null, timestamp: "2024-12-17", operatorId: "00001025406",
    auditKey: null, updateKey: null, emplTermEnd: null,
    hccConsultDates: null, deductAgreementForm: null, isSubmitted: null,
    uiCurrTarget: 0, uiFurthestTarget: 0, tabMask: "0,0,0,0",
    chklstRequired: null, chklstTimestamp: null, isRevised: null,
  },
  employeeId: null,
  checkListEnabled: true,
  integrationCenterMarketingEnabled: true,
  salesDemoEnabled: false,
  deaFlowEnabled: true,
};

export const mockStateLaw: StateLaw = {
  stateProvinceCd: "CA",
  countryCd: "US",
  stateProvincDesc: "California",
  overview: "zsRQGE",
  leavePayDesc: "Vacation payout is required upon termination.",
  reqPaymentMethodV: " ",
  payDischargeDateDesc: "At any time after a husband or wife dies, the surviving spouse or the guardian or conservator of the estate of the surviving spouse may, with submission of a proper affidavit and proof of identity, collect salary or other compensation owed.",
  payResignDateDesc: "At any time after a husband or wife dies, the surviving spouse or the guardian or conservator of the estate of the surviving spouse may, with submission of a proper affidavit and proof of identity, collect salary or other compensation owed.",
  payDeathDesc: "At any time after a husband or wife dies, the surviving spouse or the guardian or conservator of the estate of the surviving spouse may, with submission of a proper affidavit and proof of identity, collect salary or other compensation owed.",
  reqPaymentMethodIV: "C",
};

export const mockPendingTerminations: PendingTermination[] = [
  { id: "PT001", empId: "00010054747", name: "Alonso-Garcet, Melamie", company: "LD2", processDate: "2025-01-15", status: "Pending", termType: "Voluntary" },
  { id: "PT002", empId: "00010062891", name: "Chen, Michael", company: "LD2", processDate: "2025-01-18", status: "Pending", termType: "Involuntary" },
  { id: "PT003", empId: "00010071234", name: "Patel, Anita", company: "LD2", processDate: "2025-01-20", status: "In Progress", termType: "Voluntary" },
  { id: "PT004", empId: "00010045678", name: "Rodriguez, Carlos", company: "LD2", processDate: "2025-01-22", status: "Pending", termType: "Deceased" },
  { id: "PT005", empId: "00010089012", name: "Williams, Sarah", company: "LD2", processDate: "2025-01-25", status: "Pending", termType: "Voluntary" },
];

export const mockLeavePlans: LeavePlan[] = [
  { planType: "50", planName: "PTO", benefitPlan: "PTO01", accrualRate: "Biweekly", balance: 42.5, hrsTaken: 16.0, prvYrHrs: 0, payAtTermination: "Y", earnsBeginDt: "2025-01-01", earnsEndDt: "2025-12-31" },
  { planType: "51", planName: "Vacation", benefitPlan: "VAC01", accrualRate: "Biweekly", balance: 24.0, hrsTaken: 8.0, prvYrHrs: 0, payAtTermination: "Y", earnsBeginDt: "2025-01-01", earnsEndDt: "2025-12-31" },
  { planType: "52", planName: "Sick Leave", benefitPlan: "SIC01", accrualRate: "Monthly", balance: 18.0, hrsTaken: 4.0, prvYrHrs: 0, payAtTermination: "N", earnsBeginDt: "2025-01-01", earnsEndDt: "2025-12-31" },
  { planType: "53", planName: "Floating Holiday", benefitPlan: "FHL01", accrualRate: "Annual", balance: 8.0, hrsTaken: 0, prvYrHrs: 0, payAtTermination: "Y", earnsBeginDt: "2025-01-01", earnsEndDt: "2025-12-31" },
];

export const defaultEarnings: EarningsEntry[] = [
  { id: "E1", erncd: "REG", description: "Regular", hours: 80, rate: 38.46, amount: 3076.80, paymentType: "H" },
];

export const initialFormData: WizardFormData = {
  termProcessingType: "",
  termType: "",
  actionReason: "",
  lastDateWorked: "",
  terminationDate: "",
  noticeDate: "",
  payThroughDate: "",
  finalPayDueDate: "",
  rehireEligibility: "",
  dateContacted: "",
  leavePlans: mockLeavePlans,
  payAccruedLeave: true,
  earnings: defaultEarnings,
  additionalPay: 0,
  additionalPayCode: "",
  additionalPayDesc: "",
  overrideBenefits: false,
  numberOfPremiums: 1,
  numberOfBenSupp: 1,
  numberOfGenlDeds: 0,
  paymentMethod: "",
  deliveryMethod: "",
  checkDistribution: "",
  directDepositEndDate: "",
  deliveryInstructions: "",
  ddpActiveDate: "",
  mgrName: "",
  hrmContacted: "",
  hrmName: "",
  notes: "",
  sendConfirmEmail: true,
  emailAddress: "DevEmailTesting@trinet.com",
};

export const statesList = [
  "US|AL|Alabama", "US|AK|Alaska", "US|AZ|Arizona", "US|AR|Arkansas",
  "US|CA|California", "US|CO|Colorado", "US|CT|Connecticut", "US|DE|Delaware",
  "US|DC|District of Columbia", "US|FL|Florida", "US|GA|Georgia", "US|HI|Hawaii",
  "US|ID|Idaho", "US|IL|Illinois", "US|IN|Indiana", "US|IA|Iowa",
  "US|KS|Kansas", "US|KY|Kentucky", "US|LA|Louisiana", "US|ME|Maine",
  "US|MD|Maryland", "US|MA|Massachusetts", "US|MI|Michigan", "US|MN|Minnesota",
  "US|MS|Mississippi", "US|MO|Missouri", "US|MT|Montana", "US|NE|Nebraska",
  "US|NV|Nevada", "US|NH|New Hampshire", "US|NJ|New Jersey", "US|NM|New Mexico",
  "US|NY|New York", "US|NC|North Carolina", "US|ND|North Dakota", "US|OH|Ohio",
  "US|OK|Oklahoma", "US|OR|Oregon", "US|PA|Pennsylvania", "US|RI|Rhode Island",
  "US|SC|South Carolina", "US|SD|South Dakota", "US|TN|Tennessee", "US|TX|Texas",
  "US|UT|Utah", "US|VT|Vermont", "US|VA|Virginia", "US|WA|Washington",
  "US|WV|West Virginia", "US|WI|Wisconsin", "US|WY|Wyoming",
  "CA|AB|Alberta", "CA|BC|British Columbia", "CA|ON|Ontario", "CA|QC|Quebec",
];
